### Initialize Different Types of Arrays.

In [1]:
import numpy as np

In [20]:
# All Zeros Matrix.

# 1D
aZ = np.zeros(3, dtype='int64')

# 2D
bZ = np.zeros([2,3], dtype='int64')

print(aZ)
print('\n')
print(bZ)

[0 0 0]


[[0 0 0]
 [0 0 0]]


In [21]:
# All Zeros Matrix.

# 1D
aO = np.ones(3, dtype='int64')

# 2D
bO = np.ones([2,3], dtype='int64')

print(aO)
print('\n')
print(bO)

[1 1 1]


[[1 1 1]
 [1 1 1]]


In [29]:
# Any Number Filled Matrix.

#1D
aA = np.full(2, 78)

#2D
bA = np.full([5,2], 12)

aA, bA

(array([78, 78]), array([[12, 12],
        [12, 12],
        [12, 12],
        [12, 12],
        [12, 12]]))

In [44]:
# Random Number Filled Matrix.

#1D
aR = np.random.rand(3)

#2D
bR = np.random.rand(2,2)
print(aR)
print('\n')
print(bR)

[0.95166136 0.23958919 0.08136943]


[[0.25120796 0.41856327]
 [0.05488726 0.71579904]]


In [54]:
# Random Integer Filled Matrix. (fromRange, toRange, shape)

#1D
aR = np.random.randint(1,15, 2)

#2D
bR = np.random.randint(1,15 ,[2,2])
print(aR)
print('\n')
print(bR)


[12 14]


[[ 5 14]
 [ 3 10]]
